apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apache-route
  namespace: apache-namespace
spec:
  to:
    kind: Service
    name: apache-service
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None