apiVersion: v1
kind: Service
metadata:
  name: apache
  namespace: pathashala
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort